In [1]:
import numpy as np

In [56]:
random_array = np.random.randint(low=0, high=20, size=5)
negative_array = 20 - random_array
# random_array = np.array([8,1,9,4])
# negative_array = 10 - random_array
print(random_array)
print(negative_array)

print("cumSum")
random_array_cumsum = random_array.cumsum()
print(random_array_cumsum)
negative_array_cumsum = negative_array[::-1].cumsum()[::-1]
print(negative_array_cumsum, "\n")

tups = [(2, 1), (3, 1)]

for tup in tups:
    p_view = sum(random_array[:tup[0]]) + sum(negative_array[tup[0]:tup[0] + tup[1]])
    print("p_view ", random_array[:tup[0]], negative_array[tup[0]:tup[0] + tup[1]])
    print(p_view)
    n_view = sum(negative_array[:tup[0]]) + sum(random_array[tup[0]:tup[0] + tup[1]])
    print("n_view ", negative_array[:tup[0]], random_array[tup[0]:tup[0] + tup[1]])
    print(n_view)
    print("Min: ", min(p_view, n_view))


[4 5 1 9 9]
[16 15 19 11 11]
cumSum
[ 4  9 10 19 28]
[72 56 41 22 11] 

p_view  [4 5] [19]
28
n_view  [16 15] [1]
32
Min:  28
p_view  [4 5 1] [11]
21
n_view  [16 15 19] [9]
59
Min:  21


[ 1  8  9 14 20]
